name: Download Docker Images and Upload Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Read image list from file and pull each image
      - name: Pull Docker images
        run: |
          mkdir -p docker_images
          while IFS= read -r image; do
            [[ -z "$image" ]] && continue  # Skip empty lines
            [[ "$image" == *"#"* ]] && continue  # Skip comments
            echo "Pulling Docker image: $image"
            docker pull $image
            image_name=$(echo $image | sed 's/[:\/]/_/g')  # Replace ':' and '/' with '_'
            docker save $image -o docker_images/$image_name.tar
          done < images.txt

      # Step 3: Create a compressed archive of the saved Docker images
      - name: Compress Docker images
        run: |
          tar -czvf docker_images.tar.gz -C docker_images .

      # Step 4: Upload the compressed Docker images as an artifact
      - name: Upload Docker images as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker_images
          path: docker_images.tar.gz
