name: Download Docker Images and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Read image list from file and pull each image
      - name: Pull Docker images
        run: |
          mkdir -p docker_images
          while IFS= read -r image; do
            [[ -z "$image" ]] && continue  # Skip empty lines
            [[ "$image" == *"#"* ]] && continue  # Skip comments
            echo "Pulling Docker image: $image"
            docker pull $image
            image_name=$(echo $image | sed 's/[:\/]/_/g')  # Replace ':' and '/' with '_'
            docker save $image -o docker_images/$image_name.tar
          done < images.txt

      # Step 3: Create a compressed archive of the saved Docker images
      - name: Compress Docker images
        run: |
          tar -czvf docker_images.tar.gz -C docker_images .

      # Step 4: Create a release in GitHub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Docker Images Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Upload the Docker images archive to the release
      - name: Upload Docker images to Release
        uses: softprops/action-gh-release@v2
        with:
          files: docker_images.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
