name: Download Docker Images and Release

# 当推送代码到 main 分支时或者手动触发时运行
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Read image list from file and pull each image
      - name: Pull Docker images
        run: |
          mkdir -p docker_images
          while IFS= read -r image | [[ -n "$image" ]]; do
            [[ -z "$image" ]] && continue  # Skip empty lines
            [[ "$image" == *"#"* ]] && continue  # Skip comments
            echo "Pulling Docker image: $image"
            docker pull $image
            image_name=$(echo $image | sed 's/[:\/]/_/g')  # 将 ':' 和 '/' 替换为 '_'
            docker save $image -o docker_images/$image_name.tar
          done < images.txt

      - name: Generate release tag
        id: tag
        run: |
          tag_name="release-$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}"
          echo "::set-output name=tag_name::$tag_name"
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{ github.sha }}
          release_name: Release ${{ github.ref }}-${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./images
          asset_name: docker-images.tar
          asset_content_type: application/x-tar
